VSL/urls.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# VSL/URLs

"""VSL App URL Configuration"""

from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'VSL'
urlpatterns = [
    # Homepage | Log in page
    path('', auth_views.LoginView.as_view(template_name='VSL/index.html'), name='index'),
    # Log out
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Events list
    path('events/', views.events, name='events'),
    # Individual Event and it's shopping list
    path('events/<int:event_id>/', views.event, name='event'),
    # Add a new Event
    path('new_event', views.new_event, name='new_event'),
    # Edit and Event
    path('edit_event/<int:event_id>', views.edit_event, name='edit_event'),
    # Delete an event and all of it's shopping list
    path('delete_event/<int:event_id>', views.delete_event, name='delete_event'),
    # Add Item to shopping list
    path('add_item/<int:event_id>', views.add_item, name='add_item'),
    # Pillage an item on the shopping list
    path('pillage/<int:item_id>', views.pillage_item, name='pillage_item'),
    # Delete an item from the shopping list
    path('delete_item/<int:item_id>', views.delete_item, name='delete_item'),
    # set as attending an event
    path('is_attending/<int:event_id>', views.is_attending, name='is_attending'),
    # set as not attending an event
    path('not_attending/<int:event_id>', views.not_attending, name='not_attending'),
    # set as attending an event by email
    path('attending_confirmed/<int:event_id>/<uidb64>/<token>/', views.attending_confirmed, name='attending_confirmed'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# user/URLs

"""User App URL Configuration"""

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'users'
urlpatterns = [
    # User Admin - List Users, group they are in, Active status
    path('profiles/', views.profiles, name='profiles'),
    # Create a new user
    path('create_user/', views.create_user, name='create_user'),
    # Show and Edit Own user details
    path('my_profile/', views.my_profile, name='my_profile'),
    # Allow a logged in user to change their own password
    path('change_password/', views.change_password, name='change_password'),
    # Accept GDPR
    path('gdpr_confirm/', views.gdpr_confirm, name='gdpr_confirm'),
    # Recieve Emails
    path('coms_confirm/', views.coms_confirm, name='coms_confirm'),
    # Cancel Emails
    path('coms_cancel/', views.coms_cancel, name='coms_cancel'),
    # Cancel Emails from email
    path('unsubscribe/<uidb64>/<token>/', views.unsubscribe, name='unsubscribe'),
    ]

viking_shopping_list/urls.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# viking_shopping_list/URLs

"""viking_shopping_list URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('VSL.urls')),
    path('users/', include('users.urls')),
    path('users/', include('users.account_urls')),
]

VSL/models.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# VSL/Models

from django.db import models
from django.contrib.auth.models import User
import datetime


class Event(models.Model):
    """A thing (not a Viking Thing, just a thing), occuring at a particular time and place, to be attended"""
    title = models.CharField(max_length=50, help_text="Name of the glorious feasting and battle!")
    date_of = models.DateField(default=datetime.date.today, help_text="Date that the Battling and Feasting will be")
    date_added = models.DateTimeField(auto_now_add=True,)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True,)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title


class Attendance(models.Model):
    """Those who have notified that they will be attending an event."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='attending')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='attendants')
    is_attending = models.BooleanField(default=False)

    def __str__(self):
        return "%s - %s" % (self.event, self.user)


class Item(models.Model):
    """items making up the shopping list"""
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, help_text="Item to be added to shopping list.")
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='added_by')
    date_added = models.DateTimeField(auto_now_add=True,)
    is_pillaged = models.BooleanField(default=False)
    pillaged_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='pillaged_by')
    

VSL/forms.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# VSL/Forms

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.forms import ModelForm

import datetime

from .models import Event

class VSLForm(forms.Form):
    item = forms.CharField(max_length=150, widget=forms.TextInput(attrs={"placeholder": "Item Name"}))


class EventForm(forms.ModelForm):

    error_messages = {'date_error': ("The date cannot be in the past."),}

    class Meta:
        model = Event
        fields = ['title', 'date_of']
        labels = {'title:': 'Event name:', 'date_of': 'Date of:'}
        widgets = {'date_of': forms.SelectDateWidget(), 'title': forms.TextInput(attrs={"placeholder": "Event Name"})}

    def clean_date_of(self):
        date_of = self.cleaned_data['date_of']
        if datetime.date.today() > date_of:
            raise forms.ValidationError(self.error_messages['date_error'], code='date_error')
        else:
            return self.cleaned_data['date_of']

VSL/views.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# VSL/Views

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import send_mail, EmailMultiAlternatives
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template, render_to_string
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode

import datetime

from .models import Event, Item, Attendance
from users.models import OptIn
from .forms import EventForm, VSLForm
from .tokens import coms_opt_token, attend_token


def index(request):
    """Home page"""
    return render(request, 'VSL/index.html')


@login_required
def events(request):
    """Show all events"""
    events = Event.objects.order_by('date_of')
    form = EventForm(request.POST or None)
    form.is_bound
    attending = Event.objects.filter(attendants__user=request.user, attendants__is_attending=True)

    context = {'events': events, 'form': form, 'attending':attending}
    return render(request, 'VSL/events.html', context)


@login_required
def event(request, event_id):
    """show the Event and shopping list."""
    event = get_object_or_404(Event, id=event_id)
    shopping_list = event.item_set.order_by('date_added')
    form = VSLForm()
    attendee_list = User.objects.filter(attending__event=event, attending__is_attending=True)

    context = {'event': event, 'shopping_list': shopping_list, 'form': form, 'attendee_list': attendee_list}
    return render(request, 'VSL/event.html', context)


@login_required
@require_POST
def new_event(request):
    """Add a new event."""
    # Check user permission
    if request.user.has_perm('VSL.add_event'):
        form = EventForm(request.POST)
        if form.is_valid():
            new_event = Event(title=request.POST['title'])
            new_event.date_of = form.cleaned_data.get('date_of')
            new_event.added_by = request.user
            new_event.save()
            make_attendance(new_event)
            notify_new_event(request, new_event)
            return redirect('VSL:events')
        else:
            return events(request)
    else:
        'done'


def make_attendance(new_event):
    """set user as attending an event."""
    event = new_event
    users = User.objects.all()
    for user in users:
        attendance = Attendance(
            user = user, 
            event = event,
            is_attending = False
        )
        attendance.save()



@login_required
def edit_event(request, event_id):
    """Edit the details of an existing event"""
    event = Event.objects.get(id=event_id)
    if request.user.has_perm('VSL.change_event'):
        # Get the existing event data
        if request.method != 'POST':
            form = EventForm(instance=event)
        else:
            form = EventForm(instance=event, data=request.POST)
            if form.is_valid():
                form.save()
                notify_edit_event(request, event)
                return HttpResponseRedirect(reverse('VSL:event', args=[event.id]))
    else:
        'done'

    context = {'event': event, 'form': form}
    return render(request, 'VSL/edit_event.html', context)


@login_required
def delete_event(request, event_id):
    """delete an item from the shopping list"""
    event = get_object_or_404(Event, id=event_id)
    if request.user.has_perm('VSL.delete_event'):
        event.delete()
        notify_delete_event(request, event)
        return redirect('VSL:events')
    else:
        return HttpResponseRedirect(reverse('VSL:event', args=[event.id]))



@login_required
def add_item(request, event_id):
    """Add an item to the viking shopping list"""
    event = get_object_or_404(Event, id=event_id)
    form = VSLForm(request.POST)
    if request.user.has_perm('VSL.add_item'):
        if form.is_valid():
            new_item = Item(name=request.POST['item'])
            new_item.event = event
            new_item.added_by = request.user
            new_item.save()
            notify_added(request, new_item)
        return HttpResponseRedirect(reverse('VSL:event', args=[event_id]))
    else:
        return HttpResponseRedirect(reverse('VSL:event', args=[event_id]))


@login_required
def pillage_item(request, item_id):
    """ Mark an item as pillaged (purchased)"""
    item = Item.objects.get(id=item_id)
    if request.user.has_perm('VSL.change_item'):
        item.is_pillaged = True
        item.pillaged_by = request.user
        item.save()
        notify_pillaged(request, item)
        return HttpResponseRedirect(reverse('VSL:event', args=[item.event_id]))
    else:
        return HttpResponseRedirect(reverse('VSL:event', args=[item.event_id]))


@login_required
def delete_item(request, item_id):
    """delete an item from the shopping list"""
    item = Item.objects.get(id=item_id)
    if request.user.has_perm('VSL.delete_item'):
        item.delete()
        notify_deleted_item(request, item)
        return HttpResponseRedirect(reverse('VSL:event', args=[item.event_id]))
    else:
        return HttpResponseRedirect(reverse('VSL:event', args=[item.event_id]))


@login_required
def is_attending(request, event_id):
    """set user as attending an event."""
    event = get_object_or_404(Event, id=event_id)
    attendance = Attendance.objects.get(
        user = request.user, 
        event = event,
        )
    attendance.is_attending = True
    attendance.save()
    return redirect('VSL:events')


@login_required
def not_attending(request, event_id):
    """set user as NOT attending an event."""
    event = get_object_or_404(Event, id=event_id)
    attendance = Attendance.objects.get(
        user = request.user, 
        event = event,
        )
    attendance.is_attending = False
    attendance.save()
    return redirect('VSL:events')


def attending_confirmed(request, event_id, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None:
        event = Event.objects.get(id=event_id)
        attend = Attendance.objects.get(
            user = user,
            event = event,
            )
        if attend_token.check_token(attend, token):
            attendance = attend
            attendance.is_attending = True
            attendance.save()
            return render(request, 'VSL/attending_confirmed.html')
        else:
            return render(request, 'users/invalid.html')
    else:
        return render(request, 'users/invalid.html')



def make_unsub_link(request, user):
    """create a link to unsubscribe the user from notifications"""
    domain = get_current_site(request).domain
    unsub_link = render_to_string('notifications/unsub_link.txt', {
                'user':user,
                'domain':domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':coms_opt_token.make_token(user)
                })

    return unsub_link


def make_attend_link(request, event, user):
    """create a link to unsubscribe the user from notifications"""
    domain = get_current_site(request).domain
    attend = Attendance.objects.get(
            user = user, 
            event = event,
            )
    attend_link = render_to_string('notifications/attend_link.txt', {
                'user':user,
                'event':event,
                'domain':domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token':attend_token.make_token(attend)
                })

    return attend_link



def notify_added(request, new_item):
    item = new_item
    event = new_item.event
    users = User.objects.filter(opt_in__recieve_coms=True)
    site_name = get_current_site(request).name
    for user in users:
        if user.is_active and user != request.user and user.last_login != None:
            unsub_link = make_unsub_link(request, user)
            with open(settings.BASE_DIR + "/VSL/templates/notifications/item_added_email.txt") as t:
                ne_message = t.read()
                message = EmailMultiAlternatives(
                    subject = str(site_name) + " - " + str(event.title) + " - New item added.",
                    from_email = settings.EMAIL_HOST_USER,
                    to = [user.email],
                    )
                context = {'request':request, 'user':user, 'event':event, 'item':item, 'site_name':site_name, 'unsub_link':unsub_link}
                html_template = get_template("notifications/item_added_email.html").render(context)
                message.attach_alternative(html_template, "text/html")
                message.send()
        else:
            'done'


def notify_pillaged(request, item):
    item = item
    event = item.event
    users = User.objects.filter(opt_in__recieve_coms=True)
    site_name = get_current_site(request).name
    for user in users:
        if user.is_active and user != request.user and user.last_login != None:
            unsub_link = make_unsub_link(request, user)
            with open(settings.BASE_DIR + "/VSL/templates/notifications/item_pillaged_email.txt") as t:
                ne_message = t.read()
                message = EmailMultiAlternatives(
                    subject = str(site_name) + " - " + str(event.title) + " - Item pillaged.",
                    from_email = settings.EMAIL_HOST_USER,
                    to = [user.email],
                    )

VSL/templates/VSL/attending_confirmed.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/unsubscribe
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="container">
    <h2>Attendance Confirmed</h2>
</div>
{% endblock header %}


{% block content %}
<div class="container">
    <div class="row pl-3">
        <h5>
            <p>Hi {{ user }}. You have succesfully signed up to attend the {{ event }} event.</p>
            <p>You will now recieve updates for this from the Viking Shopping List.</p>
        </h5>
    </div>
</div>
<hr />
<div class="container">
    <div class="row pl-3">
        <p>Go to <a href="{% url 'VSL:index' %}" method="get"><button name="submit" class="btn btn-primary">Log in</button></a> ?</p>
    </div>
</div>
{% endblock content %}

VSL/templates/VSL/base.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 VSL/Templates/VSL/Base
-->

{% load bootstrap4 %}
{% load group_tags %}
{% load gdpr_tag %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{% load static %}
{% block static %}
<script src="{% static 'js/confirm_delete.js' %}"></script>
<script src="{% static 'js/auto_modal.js' %}"></script>
{% endblock %}
{% include 'VSL/confirm_delete_modal.html' %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Viking Shopping List</title>

</head>

<body>
    <!-- Static Navbar-->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
        <div class="container">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'VSL:events' %}">Viking Shopping List</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'VSL:index' %}">Viking Shopping List</a>
            {% endif %}
            {% if user.is_authenticated %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarmenu" aria-controls="navbarmenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% endif %}

            <div class="collapse navbar-collapse" id="navbarmenu">
                <ul class="navbar-nav mr-auto">
                    {% if request.user|has_group:"Jarls" %}
                    <li class="nav-item"><a href="{% url 'VSL:events' %}" class="nav-link">Upcoming Events</a></li>
                    <li class="nav-item"><a href="{% url 'users:profiles' %}" class="nav-link">Users Profiles</a></li>
                    {% elif user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'VSL:events' %}" class="nav-link">Upcoming Events</a></li>
                    {% endif %}
                </ul>

                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'users:my_profile' %}" class="nav-link"> {{ user.username }}</a></li>
                    <li class="nav-item"><a href="{% url 'VSL:logout' %}" class="nav-link">Log Out</a></li>
                    {% endif %}
                </ul>
            </div> <!--/.nav-collapse-->
        </div>
    </nav>

    <div class="container">
        {% if user.is_authenticated and request.user|gdpr_accept %}
        <div class="modal fade" id="ConfirmGDPRModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmGDPRModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">GDPR Compliance</h5>
                        </button>
                    </div>
                    <div class="modal-body confirm-gdpr border-light">
                        <p>While you are a member this site shall keep the following information:</p>
                        <ul>
                            <li>Email Address - Used to send optional update notifications</li>
                            <li>Name - Used to identify you in communications</li>
                            <li>Username - Used as a unique identifier</li>
                            <li>Date and Time of last log in - Enables site background functions</li>
                        </ul>
                        <p>
                            This information is required for the functioning of the site.
                            It is accessible to site administrators, but is not shared beyond that.
                            You may delete your account at any time from your profile page,
                            this will delete all record of your data.
                        </p>
                    </div>
                    <div class="modal-footer">
                        <h5>Accept and show Events</h5>
                        <a href=" {% url 'users:gdpr_confirm' %}"><button type="button" class="btn btn-success" id="ConfirmGDPRModal">Accept</button></a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <hr>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->

</body>
</html>

VSL/templates/VSL/edit_event.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 VSL/Templates/VSL/Events
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<h2>{{ event }}</h2>
<h5>Edit {{ event }}?</h5>
{% endblock header %}

{% block content %}

<div class="container pl-0">
    <form action="{% url 'VSL:edit_event' event.id %}" method="post" class="form">
        <div class="row">
            {% csrf_token %}
            <div class="col-auto">
                {% bootstrap_form form show_help=FALSE %}
                <div class="row">
                    <div class="col">
                        {% buttons %}
                        <button name="submit" class="btn btn-warning btn">Save Changes</button>
                        {% endbuttons %}
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="col-auto">
        <a href="{% url 'VSL:event' event.id %}"><button name="button" class="btn btn-primary">Cancel</button></a>
    </div>
</div>


{% endblock content %}

VSL/templates/VSL/event.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 VSL/Templates/VSL/Event
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>{{ event }}</h2>
    <h5>{{ event.date_of }}</h5>
</div>
{% endblock header %}

{% block content %}

{% if perms.VSL.add_item %}
<div class="container">
    <div class="row pl-3">
        <h4>Add item?</h4>
    </div>
    <form action="{% url 'VSL:add_item' event.id %}" method="post" class="form">
        <div class="row">
            {% csrf_token %}
            <div class="col-auto">
                {% bootstrap_form form layout='inline' %}
            </div>
            <div class="col-auto">
                {% buttons %}
                    <button name="submit" class="btn btn-success">Add Item</button>
                {% endbuttons %}
            </div>
        </div>
    </form>
</div>
<hr>
{% endif %}

<div class="container">
    <div class="row pl-3">
        <div class="col">
            <div class="row">
                <h4>Shopping List:</h4>
            </div>
            <div class="row">
                <div class="alert alert-primary pb-1">
                    <ul class="list-unstyled">
                        {% for item in shopping_list %}
                        <li>
                            {% if item.is_pillaged %}
                            <div class="alert alert-success text-dark border-primary">
                                <div class="row">
                                    <s><h5>{{ item.name }}</h5></s>
                                </div>
                                <div class="row">
                                    <small>Requested by <strong>{{ item.added_by.username }}</strong> on <strong>{{ item.date_added|date:'d M Y' }}</strong>. Pillaged by <strong>{{ item.pillaged_by.username }}</strong></small>
                                </div>
                            </div>
                            {% else %}
                            <div class="alert alert-light text-dark border-primary">
                                <div class="row">
                                    <div class="col p-0">
                                        <h5>{{ item.name }}</h5>
                                    </div>
                                    {% if perms.VSL.change_item %}
                                    <div class="col-ml-auto">
                                        <a href=" {% url 'VSL:pillage_item' item.id %}">
                                            <button name="submit" class="btn btn-success btn-sm">Pillaged!</button>
                                        </a>
                                        <a href="{% url 'VSL:delete_item' item.id %}" class="confirm-delete" title="Delete Item" data-toggle="modal" data-target="#ConfirmDeleteModal" id="deleteButton{{item.id}}">
                                            <button name="button" class="btn btn-danger btn-sm">Delete</button>
                                        </a>
                                    </div>
                                    {% endif %}
                                </div>
                                <div class="row">
                                    <small>Requested by <Strong>{{ item.added_by.username }}</Strong> on <strong>{{ item.date_added|date:'d M Y' }}</strong></small>
                                </div>
                            </div>
                            {% endif %}
                        </li>
                        {% empty %}
                        <li>
                            <div class="alert alert-light text-dark">
                                <h5>There are no items in the shopping list.</h5>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <h4>Attendees:</h4>
            </div>
            <div class="row">
                <div class="alert alert-primary pb-1">
                    <ul class="list-unstyled">
                        {% for attendee in attendee_list %}
                        <li>
                            <div class="alert alert-light text-dark border-primary pb-1">
                                <h6>{{ attendee }}</h6>
                            </div>
                        </li>
                        {% empty %}
                        <li>
                            <div class="alert alert-light text-dark">
                                <h5>There are currently no attendees to this event.</h5>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>



{% if perms.VSL.change_event %}
<hr />
<div class="container pb-5">
    <a href=" {% url 'VSL:edit_event' event.id %}"><button name="submit" class="btn btn-warning btn-sm">Edit Event</button></a> <a href="{% url 'VSL:delete_event' event.id %}" class="confirm-delete" title="Delete Event" data-toggle="modal" data-target="#ConfirmDeleteModal" id="deleteButton{{event.id}}">
            <button name="button" class="btn btn-danger btn-sm">Delete Event</button>
</div>
{% endif %}

{% endblock content %}

VSL/templates/VSL/events.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 VSL/Templates/VSL/Events
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}
{% load gdpr_tag %}

{% block header %}
<div class="container">
    <h2>Events</h2>
    <h5>Feasting and Battles! Aaaaarg!</h5>
</div>
{% endblock header %}

{% block content %}

{% if perms.VSL.add_event %}
<div class="container">
    <div class="row pl-3">
        <h4>Add a new Event?</h4>
    </div>
    <form action="{% url 'VSL:new_event' %}" method="post" class="form">
        <div class="row">
            {% csrf_token %}
            <div class="col-auto">
                {% bootstrap_field form.title show_help=FALSE layout='inline' %}
            </div>
            <div class="col-auto">
                {% bootstrap_field form.date_of show_help=FALSE layout='horizontal' %}
            </div>
            <div class="col-auto">
                {% buttons %}
                <button name="submit" class="btn btn-success">Add Event</button>
                {% endbuttons %}
            </div>
        </div>
    </form>
</div>
<hr>
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-auto">
            <div class="alert alert-primary">
                <ul class="list-unstyled">
                    {% for event in events %}
                    <li>
                        <div class="alert alert-light text-dark border-primary">
                            <div class="form-group">
                                <a href="{% url 'VSL:event' event.id %}"><h5>{{ event }}</h5></a>
                                <small>When: <strong>{{ event.date_of }}</strong>, Added: <strong>{{ event.added_by }}</strong></small>
                            </div>
                                {% if event in attending %}
                                    <a href=" {% url 'VSL:not_attending' event.id %}"><button name="submit" class="btn btn-success btn-sm" id="events">Attending</button></a>
                                {% else %}
                                    <a href=" {% url 'VSL:is_attending' event.id %}"><button name="submit" class="btn btn-outline-secondary btn-sm" id="events">Not Attending</button></a>
                                {% endif %}
                        </div>
                    </li>
                    {% empty %}
                    <li>There are currently no upcoming events.<br />Please add a new event to continue.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

VSL/templates/VSL/notification_email.html
<html>
{% load i18n %}{% autoescape off %}

<head>
    <h2>{{ event.title }} created</h2>
</head>

<hr />

<body>
    <h5>Hello {{ user.get_user_name }}</h5>
    
    <p>{{ request.user }} has created the {{ event.title }} event.</p>
    
    <p>Please go to {{ site_name }} to join in.</p>


    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

</body>
{% endautoescape %}
</html>