VSL/urls.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# VSL/URLs

"""VSL App URL Configuration"""

from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'VSL'
urlpatterns = [
    # Homepage | Log in page
    path('', auth_views.LoginView.as_view(template_name='VSL/index.html'), name='index'),
    # Log out
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Events list
    path('events/', views.events, name='events'),
    # Individual Event and it's shopping list
    path('events/<int:event_id>/', views.event, name='event'),
    # Add a new Event
    path('new_event', views.new_event, name='new_event'),
    # Edit and Event
    path('edit_event/<int:event_id>', views.edit_event, name='edit_event'),
    # Delete an event and all of it's shopping list
    path('delete_event/<int:event_id>', views.delete_event, name='delete_event'),
    # Add Item to shopping list
    path('add_item/<int:event_id>', views.add_item, name='add_item'),
    # Pillage an item on the shopping list
    path('pillage/<int:item_id>', views.pillage_item, name='pillage_item'),
    # Delete an item from the shopping list
    path('delete_item/<int:item_id>', views.delete_item, name='delete_item'),
    # set as attending an event
    path('is_attending/<int:event_id>', views.is_attending, name='is_attending'),
    # set as not attending an event
    path('not_attending/<int:event_id>', views.not_attending, name='not_attending'),
    # set as attending an event by email
    path('attending_confirmed/<int:event_id>/<uidb64>/<token>/', views.attending_confirmed, name='attending_confirmed'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# user/URLs

"""User App URL Configuration"""

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'users'
urlpatterns = [
    # User Admin - List Users, group they are in, Active status
    path('profiles/', views.profiles, name='profiles'),
    # Create a new user
    path('create_user/', views.create_user, name='create_user'),
    # Show and Edit Own user details
    path('my_profile/', views.my_profile, name='my_profile'),
    # Allow a logged in user to change their own password
    path('change_password/', views.change_password, name='change_password'),
    # Accept GDPR
    path('gdpr_confirm/', views.gdpr_confirm, name='gdpr_confirm'),
    # Recieve Emails
    path('coms_confirm/', views.coms_confirm, name='coms_confirm'),
    # Cancel Emails
    path('coms_cancel/', views.coms_cancel, name='coms_cancel'),
    # Cancel Emails from email
    path('unsubscribe/<uidb64>/<token>/', views.unsubscribe, name='unsubscribe'),
    ]

viking_shopping_list/urls.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# viking_shopping_list/URLs

"""viking_shopping_list URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('VSL.urls')),
    path('users/', include('users.urls')),
    path('users/', include('users.account_urls')),
]

users/models.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# Users/Models

from django.db import models
from django.contrib.auth.models import User


class OptIn(models.Model):
    """User confirmation of acceptance of site storing email address"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='opt_in')
    gdpr = models.BooleanField(default=False)
    recieve_coms = models.BooleanField(default=True)

users/forms.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# user/forms


from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User, Group



class AddUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'group']

    def clean_first_name(self):
        if self.cleaned_data['first_name'].strip() == '':
            raise ValidationError("First name is required.")
        return self.cleaned_data['first_name']

    def clean_last_name(self):
        if self.cleaned_data['last_name'].strip() == '':
            raise ValidationError("Last name is required.")
        return self.cleaned_data['last_name']

    def save(self, commit=True):
        user = super(AddUserForm, self).save(commit=False)
        randompass = User.objects.make_random_password()
        group = self.cleaned_data['group']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.password1 = randompass
        user.password2 = randompass

        if commit:
            user.save()
            user.groups.add(group)

        return user


class UserOwnForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

    def clean_first_name(self):
        if self.cleaned_data['first_name'].strip() == '':
            raise ValidationError("First name is required.")
        return self.cleaned_data['first_name']

    def clean_last_name(self):
        if self.cleaned_data['last_name'].strip() == '':
            raise ValidationError("Last name is required.")
        return self.cleaned_data['last_name']

    def save(self, commit=True):
        user = super(UserOwnForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

users/views.py
# Peter AC Munro Python Portfolio
# Viking Shopping List
# user/Views

import string, random
from django.conf import settings
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from django.forms import modelform_factory, modelformset_factory
from django.http import HttpRequest, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.http import require_POST

from .forms import AddUserForm, UserOwnForm

from .models import OptIn
from VSL.models import Event, Attendance
from VSL.tokens import coms_opt_token


def is_group(user):
    return user.groups.filter(name='Jarls').exists()


@login_required
@user_passes_test(is_group)
def profiles(request):
    """Show all users details"""
    userformset = modelformset_factory(User, fields=('first_name', 'last_name', 'username', 'groups',), extra=0)
    if request.method != 'POST':
        formset = userformset(queryset=User.objects.filter(is_superuser=False).order_by('last_name'))
    else:
        formset = userformset(request.POST)
        if formset.is_valid():
            formset.save()

    context = {'formset': formset}
    return render(request, 'users/profiles.html', context)


@login_required
@user_passes_test(is_group)
def create_user(request):
    """Create a new user"""
    if request.method != 'POST':
        form = AddUserForm()
    else:
        form = AddUserForm(request.POST)
        if form.is_valid():
            new_user_email = form.cleaned_data.get('email')
            new_user = form.save()
            new_optin = OptIn(user=new_user, recieve_coms=True, gdpr=False)
            new_optin.save()
            notify_new_user(new_user_email)
            return redirect('users:profiles')

    context = {'form': form}
    return render(request, 'users/create_user.html', context)


@login_required
def my_profile(request):
    """A page for a user to edit their own details"""
    attending_list = Event.objects.filter(attendants__user=request.user, attendants__is_attending=True)
    recieve_coms = OptIn.objects.get(user=request.user).recieve_coms
    if request.method != 'POST':
        form = UserOwnForm(instance=request.user)
    else:
        form = UserOwnForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:my_profile')

    context = {'userownform': form, 'attending_list':attending_list, 'recieve_coms': recieve_coms}
    return render(request, 'users/my_profile.html', context)


@login_required
def gdpr_confirm(request):
    """A function to enable the user to confirm use of email"""
    gdproptin = OptIn.objects.get(user=request.user)
    gdproptin.gdpr = True

    gdproptin.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))



@login_required
def coms_confirm(request):
    """Set user as recieving email updates"""
    comsoptin = OptIn.objects.get(user=request.user)
    comsoptin.recieve_coms = True

    comsoptin.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def coms_cancel(request):
    """set user as not receiving any email updates"""
    comsoptin = OptIn.objects.get(user=request.user)
    comsoptin.recieve_coms = False

    comsoptin.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def unsubscribe(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and coms_opt_token.check_token(user, token):
        comsoptin = user.opt_in
        comsoptin.recieve_coms = False
        comsoptin.save()
        return render(request, 'users/unsubscribe.html')
    else:
        return render(request, 'registration/invalid.html')


@login_required
def change_password(request):
    """A page for the user to change their password"""
    if request.method != 'POST':
        form = PasswordChangeForm(user=request.user)
    else:
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('users:my_profile')

    context = {'changepassform': form}
    return render(request, 'users/change_password.html', context)



def notify_new_user(new_user_email):
    """sends a password reset email to a newly created user."""
    subject = "Welcome to the Viking shopping list! Now complete your registration"
    form = PasswordResetForm({'email': new_user_email})
    if form.is_valid():
        request = HttpRequest()
        request.META['SERVER_NAME'] = 'vikingshoppinglist.herokuapp.com'
        request.META['SERVER_PORT'] = '80'
#        request.META['SERVER_NAME'] = 'localhost'
#        request.META['SERVER_PORT'] = '8000'
        form.save(
            request=request,
            use_https=True,
            from_email=settings.DEFAULT_FROM_EMAIL,
            email_template_name='users/new_user_email.txt',
            html_email_template_name='users/new_user_email.html',
            subject_template_name = 'users/new_user_subject.txt',
            )

    return 'done'

users/templates/users/change_password.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/password
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h1>Hello {{ user.username }}</h1>
    <h5>Change Password</h5>
</div>
{% endblock header %}

{% block content %}
    <div class="container">
        <div class="row pl-3">
            <form action="{% url 'users:change_password' %}" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form changepassform %}
                {% buttons %}
                <button name="submit" class="btn btn-primary">Save Changes</button>
                {% endbuttons %}
            </form>
        </div>
        <div class="row pl-3">
            <a href="{% url 'users:my_profile' %}"><button name="button" class="btn btn-warning">Cancel</button></a>
        </div>
    </div>

{% endblock content %}

users/templates/users/confirm_gdpr_modal.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/templates/users/confirm_gdpr_modal
-->
{% load bootstrap4 %}


<div class="modal fade show" id="ConfirmGDPRModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmGDPRModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">GDPR Compliance</h5>
            </div>
            <div class="modal-body confirm-gdpr border-light">
                <p>While you are a member this site shall keep the following information:</p>
                <ul>
                    <li>Email Address - Used to send optional update notifications</li>
                    <li>Name - Used to identify you in communications</li>
                    <li>Username - Used as a unique identifier</li>
                    <li>Date and Time of last log in - Enables site background functions</li>
                </ul>
                <p>
                    This information is required for the functioning of the site.
                    It is accessible to site administrators, but is not shared beyond that.
                    You may delete your account at any time from your profile page,
                    this will delete all record of your data.
                </p>
            </div>
            <div class="modal-footer">
                <a href=" {% url 'users:gdpr_confirm' %}">
                    <button type="button" class="btn btn-success">Accept</button>
                </a>
            </div>
        </div>
    </div>
</div>

users/templates/users/create_user.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/create_user
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>Create User</h2>
    <h5>New Warriors and Shield Maidens for the Pilaging! Aaaaarg!</h5>
</div>
{% endblock header %}


{% block content %}

<div class="container">
    <div class="row pl-3">
        <h4>Cancel and return to profiles?</h4>
    </div>
    <div class="row pl-3">
        <a href="{% url 'users:profiles' %}" method="get"><button name="submit" class="btn btn-primary">Cancel</button></a>
    </div>
</div>

<hr />

<div class="container">
    <div class="row pl-3">
        <h4>Add a new User?</h4>
    </div>
    <div class="row pl-3">
        <form action="{% url 'users:create_user' %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form show_label=False %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Create</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock content %}

users/templates/users/invalid.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/invalid
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="container">
    <h2>Invalid Link</h2>
</div>
{% endblock header %}


{% block content %}
<div class="container">
    <div class="row pl-3">
        <h5>
            <p>Sorry, that link is either invalid or has expired.</p>
            <p>Please log-in instead</p>
        </h5>
    </div>
    <div class="row pl-3">
        <a href="{% url 'VSL:index' %}" method="get"><button name="submit" class="btn btn-primary">Log in</button></a>
    </div>
</div>
{% endblock content %}

users/templates/users/my_profile.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/my_profile
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h1>Hello {{ user.username }}</h1>
</div>
{% endblock header %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h5>Edit Personal Details</h5>
        </div>
        <div class="col-1">

        </div>
        <div class="col">
            <h5>Events Attending</h5>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form action="{% url 'users:my_profile' %}" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form userownform %}
                {% buttons %}
                <button name="submit" class="btn btn-primary">Save Changes</button>
                {% endbuttons %}
            </form>
            <hr />
            <div class="row pl-3">
                <h5>Recieve emails</h5>
            </div>
            <div class="row pl-3">
                {% if recieve_coms %}
                    <a href=" {% url 'users:coms_cancel' %}"><button name="submit" class="btn btn-success">Recieveing</button></a>
                {% else %}
                    <a href=" {% url 'users:coms_confirm' %}"><button name="submit" class="btn btn-danger">Cancelled</button></a>
                {% endif %}
            </div>
            <hr />
            <div class="row pl-3">
                <h5>Change Password</h5>
            </div>
            <div class="row pl-3">
                <div class="row pl-3">
                    <p>Raw passwords are not stored, so there is no way to see your password, but you can change it using <a href="{% url 'users:change_password' %}"><button name="submit" class="btn btn-primary">this form.</button></a></p>
                </div>
            </div>
        </div>
        <div class="col-1">

        </div>
        <div class="col">
            <div class="row pl-3">
                <div class="alert alert-primary pb-1">
                    <ul class="list-unstyled">
                        {% for event in attending_list %}
                        <li>
                            <div class="alert alert-light text-dark border-primary">
                                <div class="row">
                                    <div class="col-auto">
                                        <h5>{{ event }}</h5>
                                    </div>
                                    <div class="col-auto ml-auto">
                                        <a href=" {% url 'VSL:not_attending' event.id %}"><button name="submit" class="btn btn-warning btn-sm" id="my_profile">Cancel</button></a>
                                    </div>
                                </div>
                            </div>
                        </li>
                        {% empty %}
                        <li>
                            <div class="alert alert-light text-dark">
                                <h5>You are not currently subscribed to any events.</h5>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<hr />

{% endblock content %}

users/templates/users/profiles.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/profiles
-->

{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>User Profiles</h2>
</div>
{% endblock header %}

{% block content %}
<div class="container">
    <div class="row pl-3">
        <h4>Add a new User?</h4>
    </div>
    <div class="row pl-3">
        <form action="{% url 'users:create_user' %}" method="get" class="form">
            {% csrf_token %}
            <button name="submit" class="btn btn-primary">Add User</button>
        </form>
    </div>
</div>

<hr />

<div class="container">
    <form action="{% url 'users:profiles' %}" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
        <div class="row form-row">
            {% bootstrap_form form exclude="groups" show_help=FALSE %}
            <div class="col-auto">
                <label>{{ form.groups.label }}</label>
                <div class="dropdown" id="groups">
                    <button class="btn btn-seconday dropdown-toggle" type="button" id="groups" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select
                    </button>
                    <div class="dropdown-menu" aria-labelledby="groups">
                        {% bootstrap_field form.groups show_help=FALSE show_label=FALSE %}
                    </div>
                </div>
            </div>
            <div class="col-auto pt-4 mt-2">
                {% buttons %}
                <button name="submit" class="btn btn-primary">Submit</button>
                {% endbuttons %}
            </div>
        </div>
        {% endfor %}
    </form>
</div>

{% endblock content %}

users/templates/users/reset_complete.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/reset_complete
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="container">
    <h2>Password Reset Complete</h2>
</div>
{% endblock header %}


{% block content %}
<div class="container">
    <div class="row pl-3">
        <h5>
            <p>Your password has been set. You may now go ahead and log in now</p>
        </h5>
    </div>
    <div class="row pl-3">
        <a href="{% url 'VSL:index' %}" method="get"><button name="submit" class="btn btn-primary">Log in</button></a>
    </div>
</div>
{% endblock content %}

users/templates/users/reset_confirm.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/reset_confirm
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>Password Reset</h2>
</div>
{% endblock header %}


{% block content %}

{% if validlink %}
<div class="container">
    <div class="row pl-3">
        <h5><p>Please enter your new password twice so we can verify that you typed it correctly</p></h5>
    </div>
    <div class="row pl-3">
        <form method="post">
            {% csrf_token %}
            {%bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Change my password</button>
            {% endbuttons %}
        </form>
    </div>
    <div class="row pl-3">
        <p>Please remember to update your log in details in your password manager of choice.</p>
        <p> We recommend <a href="https://1password.com/">1Password</a> or <a href="https://keepass.info/">KeePass</a></p>
    </div>
    {% else %}
    <div class="row pl-3">
        <div class="alert alert-danger text-dark">
            <h5>
                <p>The password reset link was invalid, possibly because it has already been used.</p>
                <p>Please request a new password reset.</p>
            </h5>
        </div>
    </div>
</div>
{% endif %}

{% endblock content %}

users/templates/users/reset_done.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/reset_done
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>Password Reset Sent</h2>
</div>
{% endblock header %}

{% block content %}
<div class="container">
    <div class="row pl-3">
        <h5>
            <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
            <br />
            <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
        </h5>
    </div>
</div>

{% endblock content %}

users/templates/users/reset_password.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/reset_password
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>Password Reset</h2>
</div>
{% endblock header %}


{% block content %}
<div class="container">
    <div class="row pl-3">
        <h5>
            Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </h5>
    </div>
    <div class="row-fluid">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Reset my password</button>
            {% endbuttons %}
        </form>
        <div class="row pl-3">
            <a href="{% url 'VSL:index' %}"><button name="button" class="btn btn-warning">Cancel</button></a>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/unsubscribe.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/unsubscribe
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}

{% block header %}
<div class="container">
    <h2>Unsubscribe Successfull</h2>
</div>
{% endblock header %}


{% block content %}
<div class="container">
    <div class="row pl-3">
        <h5>
            <p>Hi {{ user }}. You will no longer recieve <strong>any</strong> notifications from the Viking Shopping list.</p>
            <p>If you wish, you can re-enable notifications from your profile page.</p>
        </h5>
    </div>
</div>
<hr />
<div class="container">
    <div class="row pl-3">
        <p>Go to <a href="{% url 'VSL:index' %}" method="get"><button name="submit" class="btn btn-primary">Log in</button></a> ?</p>
    </div>
</div>
{% endblock content %}

users/templates/users/welcome.html
<!--
 Peter AC Munro Python Portfolio
 Viking Shopping List
 users/Templates/users/welcome
-->
{% extends "VSL/base.html" %}
{% load bootstrap4 %}


{% block header %}
<div class="container">
    <h2>Welcome to the Viking Shopping List</h2>
</div>
{% endblock header %}


{% block content %}

{% if validlink %}
<div class="container">
    <div class="row pl-3">
        <h4>Confirm your registration</h4>
    </div>
</div>

<hr>

<div class="container">
    <div class="row pl-3">
        <h5>Please enter your password twice so we can verify that you typed it correctly</h5>
    </div>
    <div class="row pl-3">
        <form method="post">
            {% csrf_token %}
            {%bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Set my password</button>
            {% endbuttons %}
        </form>
    </div>
    <div class="row pl-3">
        <p>We recommend the use of a password manager, such as <a href="https://1password.com/">1Password</a> or <a href="https://keepass.info/">KeePass</a></p>
    </div>

    {% else %}
    <div class="row pl-3">
        <div class="alert alert-danger text-dark">
            <h5>
                <p>The link was invalid, possibly because it has already been used.</p>
                <p>Please request a new invite.</p>
            </h5>
        </div>
    </div>
</div>
    {% endif %}

    {% endblock content %}